# Generated by Django 4.2.2 on 2023-07-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 16, 7, 42, 105934, tzinfo=datetime.timezone.utc)),
        ),
    ]
