# Generated by Django 4.2.2 on 2023-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
